FROM vllm/vllm-openai:nightly

# Installer git et Transformers depuis git pour supporter GLM-OCR
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*
RUN pip install git+https://github.com/huggingface/transformers.git

# Exposer le port
EXPOSE 8000
